### ISSUE TITLE
[Add publications by an author] Edoardo M. Ponti

### ISSUE THREAD

**Issue by ducdauge** [McGill-NLP/mcgill-nlp.github.io#52]
### Start

2021

### End

2022

### Author ID

3381663

**Comment by xhlulu** [comment]
Sorry there was some issues with attributing authorship due to semantic scholar assigning your first name to "E. Ponti". I corrected that by adding your semantic scholar ID to your profile in #55 

Here's the new PR: https://github.com/McGill-NLP/mcgill-nlp.github.io/pull/57/files#diff-1bcd048dd9376410f09dfacbc6e681411a7cc73c326bd9b78681d0167ad59a65

@ducdauge Let me know if that looks good and I'll merge it :)

**Comment by ducdauge** [comment]
Thanks, Xing Han! It looks like there are several inaccuracies (e.g. abbreviations) due to automatic scraping, I'll either fix them before merging or add a subset of the papers individually.

**Comment by xhlulu** [comment]
Yeah you should be able to edit it directly in the browser if you switch to that branch and press `.`

Or click this link: https://github.dev/McGill-NLP/mcgill-nlp.github.io/tree/gh-actions/process-form-issue-52-1651794061

**Comment by xhlulu** [comment]
@ducdauge do you want me to merge now and remove the papers later? or you can let me know which papers to remove.

**Comment by xhlulu** [comment]
Relevant papers have been already added previously. Closing this.
